import type { Metadata } from "next";
import { Roboto, Poppins, New_Rocker } from "next/font/google";
import { Toaster } from "sonner";
// import Providers from '@/providers/Providers';
import "@ant-design/v5-patch-for-react-19";
import Providers from "@/components/providers/Providers";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // Add required font weights
  variable: "--font-roboto", // Define a CSS variable for usage
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});
const newRocker = New_Rocker({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-new-rocker",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
	<Providers>
    <html lang="en">
      <body
        className={`${poppins.variable} ${roboto.variable} ${newRocker.variable}`}
      >
        {" "}
		<Toaster richColors position="top-center" />
        {children}
      </body>
    </html>
	</Providers>

  );
}
